# Application Name
spring.application.name=newsapp
logging.level.org.springframework=DEBUG
# Server Port
server.port=8081

# Optional Debug Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.main.allow-bean-definition-overriding=true
news.api.key=3f2c6a2cf6524f8e9dedc73c6bb60e85
System.out.println("Authorities from token: " + authorities);
logging.level.org.springframework.security=DEBUG

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:newsappdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console (optional, helpful for debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
